import os
import numpy as np
import xgboost as xgb
import joblib
from fastapi import FastAPI, HTTPException
from pydantic import BaseModel
from fastapi.middleware.cors import CORSMiddleware
from supabase import create_client, Client
from dotenv import load_dotenv

# --- 1. INITIALIZATION ---
# Load secrets from .env
load_dotenv()

SUPABASE_URL = os.getenv("SUPABASE_URL")
SUPABASE_KEY = os.getenv("SUPABASE_KEY")
LLAMA_KEY = os.getenv("LLAMAPARSE_CLOUD_API_KEY")

app = FastAPI()

# 2. ALLOW CROSS-ORIGIN (Critical for Streamlit to talk to FastAPI)
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# 3. CONNECT TO DATABASE
supabase: Client = create_client(SUPABASE_URL, SUPABASE_KEY)

# 4. SCHEMA DEFINITION FOR AI
class PredictionRequest(BaseModel):
    final_bid: float
    prime_cost: float
    overhead_pct: float
    profit_pct: float
    competitor_count: int

# 5. GLOBAL MODEL VARIABLE
ai_model = None

# This runs when the server starts
@app.on_event("startup")
async def load_model():
    global ai_model
    # Path to the JSON file generated by your training script
    model_path = "ml/tenderflow_xgboost.pkl"
    
    if os.path.exists(model_path):
        try:
            ai_model = joblib.load(model_path)
            print(f"✅ SUCCESS: XGBoost model loaded from {model_path}")
        except Exception as e:
            print(f"❌ ERROR: Model failed to load: {e}")
    else:
        print(f"⚠️ WARNING: {model_path} not found! Run the training script (ml/trainModels.py) first.")

# --- 6. ROUTES ---

@app.get("/")
def home():
    return {
        "message": "TenderFlow Backend is Running!",
        "model_loaded": ai_model is not None
    }

@app.get("/tenders")
def get_tenders():
    """Pulls data from your Supabase 'tenders' table"""
    try:
        response = supabase.table("tenders").select("*").execute()
        return response.data
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Supabase Error: {str(e)}")

@app.post("/predict-win-confidence")
async def predict_win(data: PredictionRequest):
    """Calculates win probability using the loaded XGBoost model"""
    if ai_model is None:
        raise HTTPException(status_code=503, detail="AI Model not loaded on server. Check logs.")
    
    try:
        # Prepare feature vector for XGBoost
        # IMPORTANT: The order of features MUST match the order used during model training
        features = np.array([[
            data.final_bid, 
            data.prime_cost, 
            data.overhead_pct, 
            data.profit_pct, 
            data.competitor_count
        ]])
        
        # Inference: predict_proba returns [prob_loss, prob_win]
        probs = ai_model.predict_proba(features)
        win_confidence = float(probs[0][1]) # Index 1 is the 'Win' class
        
        return {
            "confidence": win_confidence,
            "status": "success"
        }
    except Exception as e:
        print(f"❌ PREDICTION ERROR: {e}")
        raise HTTPException(status_code=500, detail=str(e))

if __name__ == "__main__":
    import uvicorn
    # This starts the server on port 8000
    uvicorn.run(app, host="127.0.0.1", port=8000)